s=input()
c=s.strip()
n=c.lower().replace(".","")
w=n.split()
su="-".join(w)
u=n.upper()
p=u.find("PYTHON")
print(f"Cleaned: {c}")
print(f"Normalized: {n}")
print(f"Words: {w}")
print(f"Slug: {su}")
print(f"Uppercase: {u}")
print(f"Python Position: {p}")